# This YAML describes a Waveshare ESP32S3-ePaper-1.54 development board
# Author: GHF - Nov-2025
#
esphome:
  name: esp32eink
  friendly_name: esp32eink
  on_boot:
    then:
      - pcf85063.read_time: # read the RTC time once when the system boots
      - output.turn_on: vbat_power_enable # "connect" battery
      - output.turn_on: epd_power_enable # turn ePaper display on

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
  variant: ESP32S3
  cpu_frequency: 80MHz

logger:

api:
  encryption:
    key: "mLBU7EOr5Z8rTQFDuwNwVB2CRnwSQ2oK53d4s6msTww="
  on_client_connected:
    - display.page.show: pg_main
    - component.update: my_display

ota:
  - platform: esphome
    password: "fbf9579d796ebb9a1610ac6e35741145"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH
  manual_ip:
    static_ip: 192.168.0.207
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1

  ap:
    ssid: "Esp32Eink Fallback Hotspot"
    password: "cIxc2eqnrfzE"

captive_portal:

output:
  - platform: gpio
    pin: GPIO6 # EPD3V3_EN pin GHF: Required by the ePaper display!!!
    id: epd_power_enable
    inverted: True
  - platform: gpio
    pin: GPIO17 # BATT_Control pin GHF: Required by the battery to work!!!
    id: vbat_power_enable

spi:
  clk_pin: GPIO12 # SCK
  mosi_pin: GPIO13 # SDO

i2c:
  sda: GPIO47
  scl: GPIO48

display:
  - platform: waveshare_epaper
    model: 1.54inv2 # 200x200 pixels
    cs_pin: GPIO11 # CS (Chip Select)
    dc_pin: GPIO10 # DC (Data/Command)
    busy_pin: GPIO8 # BUSY pin (required to check when the display is ready)
    reset_pin: GPIO9 # RST (Reset)
    update_interval: 300s
    reset_duration: 2ms
    full_update_every: 1
    rotation: 90
    id: my_display
    pages:
      - id: pg_offline
        lambda: |-
          //it.filled_rectangle(0, 0, 200, 200, COLOR_OFF);
          it.printf(100, 100, id(font_24), TextAlign::CENTER, "Starting");
      - id: pg_main
        lambda: |-
          it.filled_rectangle(0, 0, 200, 200, COLOR_ON);
          it.filled_rectangle(0, 0, 200, 200, COLOR_OFF);
          it.printf(100,0,id(font_36), TextAlign::TOP_CENTER, "T:%.1fC", id(local_temp).state);
          it.printf(100,40,id(font_36), TextAlign::TOP_CENTER, "H:%.1f%%", id(local_humidity).state);
          it.printf(100,80,id(font_36), TextAlign::TOP_CENTER, "B:%.2fV", id(batt_voltage).state);
          it.printf(100,170,id(font_24), TextAlign::CENTER, "WaveShare");
          it.strftime(0,199, id(font_16), TextAlign::BOTTOM_LEFT, "%Y-%m-%d", id(time_rtc).now());
          it.strftime(199,199, id(font_16), TextAlign::BOTTOM_RIGHT, "%H:%M", id(time_rtc).now());
      - id: pg_off
        lambda: |-
          it.filled_rectangle(0, 0, 200, 200, COLOR_OFF);
          //it.printf(100, 100, id(font_36), TextAlign::CENTER, "OFF");

font:
  - file: "fonts/LiberationMono-Bold.ttf" 
    id: font_36
    size: 36

  - file: "fonts/Pervitina-Dex-FFP.ttf"
    id: font_24
    size: 24

  - file: "fonts/LiberationMono-Bold.ttf"
    id: font_16
    size: 16

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status

  - platform: gpio # Generic button usable by HomeAssistant
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Button 0"
    id: button_0

  - platform: gpio # Power button, to poweroff board when on battery
    pin:
      number: GPIO18
      mode: 
        input: true
        pullup: true
      inverted: True
    id: button_pwr
    on_press: # internally disconnects the battery
      then:
        - display.page.show: pg_off
        - component.update: my_display
        - output.turn_off: vbat_power_enable
        # the rest of this code runs only if USB power is connected
        - display.page.show: pg_main 
        - component.update: my_display
        - output.turn_on: vbat_power_enable

time:
  - platform: homeassistant
    id: time_comp
    #timezone: "UTC+3"  
    timezone: "America/Argentina/Buenos_Aires"
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        pcf85063.write_time:
  - platform: pcf85063
    id: time_rtc
    update_interval: never
    timezone: "America/Argentina/Buenos_Aires"

sensor:
  - platform: shtcx
    temperature:
      name: "Temperature"
      id: local_temp
    humidity:
      name: "Humidity"
      id: local_humidity
  - platform: adc
    pin: GPIO4
    name: "Batt_voltage"
    id: batt_voltage
    attenuation: auto
    filters:
      - multiply: 2.02

#deep_sleep:
#  sleep_duration: 30s 
#  run_duration: 60s
